name: Check PR title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^((KIEV21DEVS)\-[0-9]{1,4}) ' # Regex the title should match.
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 25 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}